# Generated by Django 4.2.7 on 2024-02-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
