# Generated by Django 4.2.7 on 2024-02-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_postinfo_mobile_alter_postinfo_mobile_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinfo',
            name='code_post',
            field=models.CharField(max_length=10),
        ),
    ]
